cat > render.yaml << 'EOF'
services:
  - type: web
    name: marketplace-app
    env: php
    plan: free
    region: frankfurt
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
    startCommand: php artisan serve --host=0.0.0.0 --port=$PORT
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stderr
    disk:
      name: php-disk
      mountPath: /opt/render/project/src/storage
      sizeGB: 1
EOF
